# 50 Numpy Methods

In [1]:
import numpy as np

In [2]:
l= range(100000)

In [3]:
d= np.arange(100000)

In [4]:
%time for i in range(1,10): y= [x*2 for x in l]
    

Wall time: 88.9 ms


In [5]:
%time for i in range(1,10): c= d*2

Wall time: 1e+03 µs


In [6]:
#method#1
y = np.array([5, 1, 9, 8, 7,85,54,24,62,78,21,13,50])

In [7]:
#method#2
y.sum()

417

In [8]:
#method#3
y.min()

1

In [9]:
#method#4
y.max()

85

In [11]:
#method#5
y.argmin()

1

In [13]:
#method#6
y.argmax()

5

In [14]:
#method#7
np.all([False, True, True, True])

False

In [15]:
#method#8
np.any([True, True, True, False])

True

In [16]:
#method#9
a = np.zeros((100, 100))
np.any(a != 0)

False

In [17]:
#method#10
np.all(a == a)

True

In [18]:
#method#11
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

True

In [19]:
#method#12
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
#method#13
arr = np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [21]:
#method#14
arr = np.diag([1,5,3,7])
arr

array([[1, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 7]])

In [22]:
#method#15
np.diag(arr)

array([1, 5, 3, 7])

In [23]:
#method#16
arr = np.random.randint(1,10,3)
arr

array([3, 3, 1])

In [24]:
#method#17
arr = np.random.rand(5)
arr

array([0.33201966, 0.89857473, 0.94561472, 0.13206286, 0.74807276])

In [25]:
#method#18
arr = np.random.rand(2, 3)
arr

array([[0.09070156, 0.19039792, 0.87567664],
       [0.5737843 , 0.72261486, 0.34124129]])

In [26]:
#method#19
arr = np.random.randn(5)
arr

array([-0.65010564,  1.54918852,  0.27329971, -0.63078182, -0.38703963])

In [27]:
#method#20
arr = np.arange(2,15,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14])

In [28]:
#method#21
arr = np.arange(2, 14)
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [29]:
#method#22
np.sin(np.pi/2.)

1.0

In [30]:
#method#23
np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180. )

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [31]:
#method#24
from math import pi
np.tan(np.array([-pi,pi/2,pi]))

array([ 1.22464680e-16,  1.63312394e+16, -1.22464680e-16])

In [32]:
#method#25
np.round(16.055, 2), round(16.055, 2)  # equals 16.0549999999999997

(16.06, 16.05)

In [33]:
#method#26
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

In [34]:
#method#27
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.ceil(a)

array([-1., -1., -0.,  1.,  2.,  2.,  2.])

In [35]:

#method#28
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.trunc(a)

array([-1., -1., -0.,  0.,  1.,  1.,  2.])

In [36]:
#method#29
a = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(a)
print("Test begins")
print(np.isnan(a))

Original array
[ 1.  0. nan inf]
Test begins
[False False  True False]


In [37]:
#method#30
X = np.array([1, 75, 103, 10005])
print("Original array:")
print(X)
print("Size of the memory occupied by the said array:")
print("%d bytes" % (X.size * X.itemsize))

Original array:
[    1    75   103 10005]
Size of the memory occupied by the said array:
16 bytes


In [38]:
#method#31
array=np.arange(135,160)
print("Array of the integers from 135 to 160")
print(array)

Array of the integers from 135 to 160
[135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152
 153 154 155 156 157 158 159]


In [39]:
#method#32
array=np.arange(30,71,2)
print("Array of all the even integers from 30 to 70")
print(array) 

Array of all the even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [40]:
#method#33
array_2D=np.identity(4)
print('4x4 matrix:')
print(array_2D)

4x4 matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [41]:

#method#34
a = np.arange(10,22).reshape((3, 4))
print("Original array:")
print(a)

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [42]:
#method#35
print("Each element of the array is:")
for x in np.nditer(a):
  print(x,end=" ")

Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

In [43]:
#method#36
v = np.arange(15,55)
print("Original vector:")
print(v)
print("All values except the first and last of the said vector:")
print(v[4:-3])

Original vector:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
All values except the first and last of the said vector:
[19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42
 43 44 45 46 47 48 49 50 51]


In [44]:
#method#37
x = np.random.randint(0, 11, 5)
print("5 random numbers betwwen values")
print(x)

5 random numbers betwwen values
[4 3 7 7 9]


In [45]:
#method#38
m= np.arange(1,13).reshape((4, 3))
print("Original matrix:")
print(m)
print("Number of rows and columns of the said matrix:")
print(m.shape)

Original matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Number of rows and columns of the said matrix:
(4, 3)


In [46]:
#method#39
x = np.array([4, 5])
y = np.array([7, 10])
print("Original vectors:")
print(x)
print(y)
print("Inner product of said vectors:")
print(np.dot(x, y))

Original vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
78


In [47]:
#method#40
np.prod([])

1.0

In [48]:
#method#41
np.prod([[1.,2.],[3.,4.]])

24.0

In [49]:
#method#42
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
#method#43
np.cumsum(a,axis=0)

array([[1, 2, 3],
       [5, 7, 9]], dtype=int32)

In [51]:
#method#44
np.lcm(12, 20)

60

In [52]:
#method#45
np.gcd(12, 20)

4

In [53]:
#method#46
x = np.arange(4).reshape((2, 2))
x

array([[0, 1],
       [2, 3]])

In [54]:
#method#47
np.transpose(x)

array([[0, 2],
       [1, 3]])

In [55]:
#method#48
c = np.array(['A1B C', '1BCA', 'BCA1']) 
c

array(['A1B C', '1BCA', 'BCA1'], dtype='<U5')

In [56]:

#method#49
np.char.lower(c)

array(['a1b c', '1bca', 'bca1'], dtype='<U5')

In [57]:
#method#50
c = np.array(['a1b c', '1bca', 'bca1'])
c

array(['a1b c', '1bca', 'bca1'], dtype='<U5')

In [58]:
c = np.array(['aAaAaA', '  aA  ', 'abBABba'])
c

array(['aAaAaA', '  aA  ', 'abBABba'], dtype='<U7')

In [59]:
np.char.count(c, 'aA')

array([3, 1, 0])

In [60]:
matrix = np.random.randint(1,4,9).reshape(3,3)
matrix

array([[1, 2, 2],
       [1, 1, 1],
       [1, 1, 2]])

In [61]:
np.min(matrix, axis=1)

array([1, 1, 1])

In [62]:
np.max(matrix, axis=0)

array([1, 2, 2])

In [63]:
np.sum(matrix, axis=1)

array([5, 3, 4])

In [64]:
np.cumsum(matrix)

array([ 1,  3,  5,  6,  7,  8,  9, 10, 12], dtype=int32)

In [65]:
np.random.seed(122)
arr = np.random.randint(1,21,10)
arr

array([16, 11, 13, 17, 13, 16,  3, 16, 11, 10])

In [66]:
#Assignment By Muhammad Noman Ashraf